// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-z6VognVw5zDSWat-GA8HR0nNGjAMQIA',
    appId: '1:921001407017:web:25161589ba515b328f6238',
    messagingSenderId: '921001407017',
    projectId: 'library-app-28150',
    authDomain: 'library-app-28150.firebaseapp.com',
    storageBucket: 'library-app-28150.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKBbWmKvtW5BoUGFlK8-e5J74axeSxns',
    appId: '1:921001407017:android:a5117c489a73b90a8f6238',
    messagingSenderId: '921001407017',
    projectId: 'library-app-28150',
    storageBucket: 'library-app-28150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzB56paACOuOxpY_5rz51_8DgBNrG0gFg',
    appId: '1:921001407017:ios:99b0ea15a0ab25f88f6238',
    messagingSenderId: '921001407017',
    projectId: 'library-app-28150',
    storageBucket: 'library-app-28150.appspot.com',
    androidClientId: '921001407017-atlfn36fsbk36nrh1qnt23lqenghbl90.apps.googleusercontent.com',
    iosBundleId: 'com.library.libApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzB56paACOuOxpY_5rz51_8DgBNrG0gFg',
    appId: '1:921001407017:ios:99b0ea15a0ab25f88f6238',
    messagingSenderId: '921001407017',
    projectId: 'library-app-28150',
    storageBucket: 'library-app-28150.appspot.com',
    androidClientId: '921001407017-atlfn36fsbk36nrh1qnt23lqenghbl90.apps.googleusercontent.com',
    iosBundleId: 'com.library.libApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-z6VognVw5zDSWat-GA8HR0nNGjAMQIA',
    appId: '1:921001407017:web:274210e1206460268f6238',
    messagingSenderId: '921001407017',
    projectId: 'library-app-28150',
    authDomain: 'library-app-28150.firebaseapp.com',
    storageBucket: 'library-app-28150.appspot.com',
  );
}
